<?php

return [

    'list' => [
        'The Royal Bank of Scotland Berhad',
        'Affin Bank Berhad',
        'Alliance Bank Malaysia Berhad',
        'AmBank (M) Berhad',
        'Bangkok Bank Berhad',
        'CIMB Bank Berhad',
        'Bank of America Malaysia Berhad',
        'Bank of China (Malaysia) Berhad',
        'Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad',
        'Citibank Berhad',
        'Deutsche Bank (Malaysia) Berhad',
        'EON Bank Berhad',
        'Hong Leong Bank Berhad',
        'HSBC Bank Malaysia Berhad',
        'J.P. Morgan Chase Bank Berhad',
        'Malayan Banking Berhad',
        'OCBC Bank (Malaysia) Berhad',
        'Public Bank Berhad',
        'RHB Bank Berhad',
        'Standard Chartered Bank Malaysia Berhad',
        'The Bank of Nova Scotia Berhad',
        'United Overseas Bank (Malaysia) Berhad',
        'Affin Islamic Bank Berhad',
        'Al Rajhi Banking & Investment Corporation (Malaysia) Berhad',
        'AmIslamic Bank Berhad',
        'Asian Finance Bank Berhad',
        'Bank Islam Malaysia Berhad',
        'Bank Muamalat Malaysia Berhad',
        'CIMB Islamic Bank Berhad',
        'EONCAP Islamic Bank Berhad',
        'Hong Leong Islamic Bank Berhad',
        'Kuwait Finance House (Malaysia) Berhad',
        'RHB ISLAMIC Bank Berhad',
        'Maybank Islamic Berhad',
        'Alliance Islamic Bank Berhad',
        'HSBC Amanah Malaysia Berhad',
        'Standard Chartered Saadiq Berhad',
        'Public Islamic Bank Berhad',
        'OCBC Al-Amin Bank Berhad',
    ],

];
